ResultDB: Enable FixFieldMasksForJSON for Recorder server
FieldMask proto is not supported by Go protojson class and this is a
well-known issue in golang/protobuf (https://github.com/golang/protobuf/issues/745).
Currently, when a client (e.g. test_runner) calls ResultDB RPC and sends
a request with the FieldMask proto, the server cannot parse the
client-side json into server-side proto correctly. Here is the example
error: https://logs.chromium.org/logs/chromeos/led/zhihuixie_google.com/f3e9e982859f37d2940c9ab659a312b8a7a0f5856f3f1b894d4a00b6e3db8cf6/+/u/configure_resultdb_bigquery_export/mark_resultdb_invocation_for_bigquery_export/stderr?format=raw

LUCI infra has already had a workaround in the decoding.go (https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/2288679)
and it's managed by a flag. We have enabled it in ResultDB RPC server
before and we want to enable it in Recorder RPC server as well since the
UpdateInvocation RPC interacts with the FieldMask proto.

BUG=b:226263201
TEST=Manual Testing

Change-Id: I39e3b13dcea41645f0d961a571a9e268f2013c4a
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/3627189
Commit-Queue: Zhihui Xie <zhihuixie@google.com>
Auto-Submit: Zhihui Xie <zhihuixie@google.com>
Reviewed-by: Matthew Warton <mwarton@google.com>