[server] allow to filter out server/tq task errors.
Before, logs looke like:
  Error: <some task error>
which are hard to filter out w/o accidentally filtering out additional
logs I care to notice.

After, logs look like:
  server/tq task error: <some task error>
so accidental filtering is unlikely.

R=vadimsh

Change-Id: Ide387a8eb7db3d1a8cc5fb359e71103aac896296