[cipd] Recognize broken JSON key as a fatal error.
Before this CL:
[... service.go:91 E] Failed to load private key JSON - invalid character '/'
[... remote.go:125 W] cipd: connectivity error (Get ...: invalid character '/')
[... remote.go:125 W] cipd: retrying request to ...
<keeps trying>

After this CL:
[... service.go:91 E] Failed to load private key JSON - invalid character '/'
Error: Get ...: invalid service account credentials.

This is especially important for 'puppet-check-updates' subcommand that has
special treatment for transient errors (because puppet's "onlyif" logic is
retarded). Due to this bug, if the service account key is broken, puppet thinks
everything is up-to-date.

R=iannucci@chromium.org, tandrii@chromium.org

Change-Id: Ifa76f6d99f4436c4976e0c98f7d424710482eefb