Update patch set 4
Patch Set 4:

(1 comment)

After my change to lucicfg/starlark/stdlib/internal/luci/generators.star, the tests tell me to run go generate.

However, when I run go generate I get the following:

--- FAIL: TestExamples (0.00s)
    --- FAIL: TestExamples/02-ci-and-try (0.04s)
        examples_test.go:43: string has no .append field or method
FAIL
FAIL    go.chromium.org/luci/lucicfg    0.155s
FAIL
examples_test.go:15: running "go": exit status 1


Any ideas?

Patch-set: 4
Reviewer: Gerrit User 1272456 <1272456@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>