Update patch set 1
Patch Set 1:

It looked like this:

Traceback (most recent call last):
  @stdlib//internal/luci/generators.star:215: in gen_buildbucket_cfg
  @stdlib//internal/luci/generators.star:252: in _buildbucket_builders
  @stdlib//internal/luci/generators.star:297: in _buildbucket_dimensions
Error: NoneType value is not iterable

Which is not very useful (doesn't even have a reference to the bad builder)

Patch-set: 1
Reviewer: Gerrit User 1002539 <1002539@3ce6091f-6c88-37e8-8c75-72f92ae8dfba>
Work-in-progress: false