Revert "[vpython] Simplify and parallelize wheel installation."
This reverts commit e0aa40d7245e053bde3af8896074f3b37ceda705.

Reason for revert: This fails for some of the wheels we have:

[E2018-02-01T17:52:00.511022-08:00 37525 0 venv.go:745] wheel install "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython_bootstrap788297913/packages/pyopenssl-17.2.0-py2.py3-none-any.whl": Traceback (most recent call last):
  File "/Users/iannucci/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/iannucci/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/private/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/__main__.py", line 17, in <module>
    sys.exit(main())
  File "/private/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/__main__.py", line 14, in main
    sys.exit(wheel.tool.main())
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/tool/__init__.py", line 356, in main
    args.func(args)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/tool/__init__.py", line 299, in install_f
    args.wheel_dirs, args.force, args.list_files)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/tool/__init__.py", line 221, in install
    wf.install(force=force)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/install.py", line 268, in install
    if self.parsed_wheel_info['Root-Is-Purelib'] == 'true':
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/decorator.py", line 17, in __get__
    val = self.wrapped(inst)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/install.py", line 238, in parsed_wheel_info
    return read_pkg_info_bytes(self.zipfile.read(self.wheelinfo_name))
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/decorator.py", line 17, in __get__
    val = self.wrapped(inst)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/install.py", line 232, in zipfile
    self.verify(vzf)
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/install.py", line 385, in verify
    record = zipfile.read(record_name)
  File "/Users/iannucci/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 938, in read
    return self.open(name, "r", pwd).read()
  File "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython076907013/cd95f7/lib/python2.7/site-packages/wheel/install.py", line 437, in open
    ef = zipfile.ZipFile.open(self, name_or_info, mode, pwd)
  File "/Users/iannucci/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 964, in open
    zinfo = self.getinfo(name)
  File "/Users/iannucci/homebrew/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 912, in getinfo
    'There is no item named %r in the archive' % name)
KeyError: "There is no item named 'pyopenssl-17.2.0.dist-info/RECORD' in the archive"
 {"error":"exit status 1"}
[E2018-02-01T17:52:00.600799-08:00 37525 0 annotate.go:242] original error: exit status 1
[E2018-02-01T17:52:00.600829-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.600837-08:00 37525 0 annotate.go:242] goroutine 98:
[E2018-02-01T17:52:00.600845-08:00 37525 0 annotate.go:242] From frame 0 to 0, the following wrappers were found:
[E2018-02-01T17:52:00.600856-08:00 37525 0 annotate.go:242]   internal reason: MultiError 1/1: following first non-nil error.
[E2018-02-01T17:52:00.600869-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.600877-08:00 37525 0 annotate.go:242] #0 go.chromium.org/luci/vpython/venv/venv.go:746 - venv.(*Env).installWheels.func1.1()
[E2018-02-01T17:52:00.600885-08:00 37525 0 annotate.go:242]   reason: failed to install "/var/folders/9s/n0cjtdts60l2zdskcypggysc0056bp/T/vpython_bootstrap788297913/packages/pyopenssl-17.2.0-py2.py3-none-any.whl"
[E2018-02-01T17:52:00.600900-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.600908-08:00 37525 0 annotate.go:242] #1 go.chromium.org/luci/common/sync/parallel/runner.go:51 - parallel.(*WorkItem).execute()
[E2018-02-01T17:52:00.600922-08:00 37525 0 annotate.go:242] #2 go.chromium.org/luci/common/sync/parallel/runner.go:150 - parallel.(*Runner).dispatchLoopBody.func1()
[E2018-02-01T17:52:00.600930-08:00 37525 0 annotate.go:242] #3 runtime/asm_amd64.s:2337 - runtime.goexit()
[E2018-02-01T17:52:00.600939-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.600947-08:00 37525 0 annotate.go:242] goroutine 5:
[E2018-02-01T17:52:00.600955-08:00 37525 0 annotate.go:242] #0 go.chromium.org/luci/vpython/venv/venv.go:754 - venv.(*Env).installWheels()
[E2018-02-01T17:52:00.600967-08:00 37525 0 annotate.go:242]   reason: failed to install wheels
[E2018-02-01T17:52:00.600974-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.600982-08:00 37525 0 annotate.go:242] #1 go.chromium.org/luci/vpython/venv/venv.go:528 - venv.(*Env).createLocked.func1()
[E2018-02-01T17:52:00.600990-08:00 37525 0 annotate.go:242]   reason: failed to install wheels
[E2018-02-01T17:52:00.600998-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.601005-08:00 37525 0 annotate.go:242] #2 go.chromium.org/luci/common/system/filesystem/tempdir.go:55 - filesystem.(*TempDir).With()
[E2018-02-01T17:52:00.601014-08:00 37525 0 annotate.go:242] #3 go.chromium.org/luci/vpython/venv/venv.go:104 - venv.withTempDir()
[E2018-02-01T17:52:00.601022-08:00 37525 0 annotate.go:242] #4 go.chromium.org/luci/vpython/venv/venv.go:498 - venv.(*Env).createLocked()
[E2018-02-01T17:52:00.601030-08:00 37525 0 annotate.go:242] #5 go.chromium.org/luci/vpython/venv/venv.go:273 - venv.(*Env).ensure.func1()
[E2018-02-01T17:52:00.601038-08:00 37525 0 annotate.go:242]   reason: failed to create new VirtualEnv
[E2018-02-01T17:52:00.601045-08:00 37525 0 annotate.go:242]
[E2018-02-01T17:52:00.601053-08:00 37525 0 annotate.go:242] #6 go.chromium.org/luci/vpython/venv/venv.go:971 - venv.mustReleaseLock()
[E2018-02-01T17:52:00.601061-08:00 37525 0 annotate.go:242] #7 go.chromium.org/luci/vpython/venv/venv.go:259 - venv.(*Env).ensure()
[E2018-02-01T17:52:00.601069-08:00 37525 0 annotate.go:242] #8 go.chromium.org/luci/vpython/venv/venv.go:329 - venv.(*Env).withImpl()
[E2018-02-01T17:52:00.601077-08:00 37525 0 annotate.go:242] #9 go.chromium.org/luci/vpython/venv/venv.go:169 - venv.With()
[E2018-02-01T17:52:00.601085-08:00 37525 0 annotate.go:242] #10 go.chromium.org/luci/vpython/run.go:63 - vpython.Run()
[E2018-02-01T17:52:00.601095-08:00 37525 0 annotate.go:242] #11 go.chromium.org/luci/vpython/application/application.go:314 - application.(*application).mainImpl()
[E2018-02-01T17:52:00.601105-08:00 37525 0 annotate.go:242] #12 go.chromium.org/luci/vpython/application/application.go:398 - application.(*Config).Main.func1()
[E2018-02-01T17:52:00.601113-08:00 37525 0 annotate.go:242] #13 go.chromium.org/luci/vpython/application/support.go:47 - application.run()
[E2018-02-01T17:52:00.601121-08:00 37525 0 annotate.go:242] #14 go.chromium.org/luci/vpython/application/application.go:397 - application.(*Config).Main()
[E2018-02-01T17:52:00.601129-08:00 37525 0 annotate.go:242] #15 infra/tools/vpython/main.go:92 - vpython.mainImpl()
[E2018-02-01T17:52:00.601136-08:00 37525 0 annotate.go:242] #16 infra/tools/vpython/main_test.go:301 - vpython.testMainRunDelegate()
[E2018-02-01T17:52:00.601145-08:00 37525 0 annotate.go:242] #17 infra/tools/vpython/main_test.go:61 - vpython.TestMain()
[E2018-02-01T17:52:00.601152-08:00 37525 0 annotate.go:242] #18 testing/testing.go:746 - testing.tRunner()
[E2018-02-01T17:52:00.601160-08:00 37525 0 annotate.go:242] #19 runtime/asm_amd64.s:2337 - runtime.goexit()

Original change's description:
> [vpython] Simplify and parallelize wheel installation.
> 
> Wheel installation is roughly a python 'unzip' operation. Currently we
> use `pip` with lots of arguments to trick it into only installing all the
> wheels from a local directory. It currently does a bunch of (unnecessary)
> dependency resolution, followed by serially unzipping each wheel using
> python's builtin unzip support.
> 
> This CL replaces the single pip invocation with a parallel set of direct
> `wheel install` invocations. Wheel install is a much simpler operation (no
> dependency resolution, etc.), and is safe to parallelize in this context
> (since we've already selected a compatible set of wheels).
> 
> This yields about a 30% speedup on my '14 MacBook Pro (w/ SSD). I
> expect to see a much greater speedup on machines with spinning rust
> and/or Windows.
> 
> As a happy side-effect, this removes the need for the `vpython/wheel`
> package, since vpython entirely outsources the job of wheel name parsing
> to the python `wheel` command.
> 
> R=​dnj@chromium.org, vadimsh@chromium.org
> 
> Bug: 804174
> Change-Id: I65a5dfff122a17852d6ee4a210bd3ad89b59c6e4
> Reviewed-on: https://chromium-review.googlesource.com/896948
> Commit-Queue: Robbie Iannucci <iannucci@chromium.org>
> Reviewed-by: Daniel Jacques <dnj@chromium.org>
> Reviewed-by: Nodir Turakulov <nodir@chromium.org>

TBR=iannucci@chromium.org,vadimsh@chromium.org,dnj@chromium.org,nodir@chromium.org

Change-Id: I2b7576ae487c24041d3a88983751beabb4efc7fd
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 804174