[cipd] Reply with HTTP 405 on unsupported legacy endpoints.
The error message surfaces in legacy clients as:

"""
Error: unexpected reply (HTTP 405):
This version of CIPD client is no longer supported, please upgrade.
"""

They'll see it whenever they use something other than 'ensure', 'selfupdate',
or 'install'.

R=nodir@chromium.org, tandrii@chromium.org
BUG=801423

Change-Id: Id95f7ca8e7147be23dce7c962bf088b2dc5b25e8