[lucicfg] Improve rendering of errors with backtraces.
Also move relevant code into a dedicated package.

Previously, annotating such errors "swallowed" the backtrace,
resulting in e.g.

```
loading PACKAGE.star: in declare: bad package name "infra": must start with @
```

Now an annotated backtracable error is rendered as e.g.

```
Error: loading PACKAGE.star:
Traceback (most recent call last):
  //PACKAGE.star:1:12: in <toplevel>
  @stdlib//builtins.star:53:23: in _declare
Error in declare: bad package name "infra": must start with @
```

Depends on string hax, since errors aren't very examinable.

R=iannucci@chromium.org

Change-Id: If5c508de99833addbb1f3fcdc8bd22686987986d
Reviewed-on: https://chromium-review.googlesource.com/c/infra/luci/luci-go/+/6354394
Commit-Queue: Vadim Shtayura <vadimsh@chromium.org>
Reviewed-by: Robbie Iannucci <iannucci@google.com>